### ISSUE TITLE
Support for 0.60 autolinking

### ISSUE THREAD

**Issue by undebugged** [Backendless/React-Native-JS-SDK#2]
On creating a new project and adding the packages, after running react-native-link: 

gabriel@Gabriels-MacBook Backendless % react-native link
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - backendless-react-native: https://npmjs.com/package/backendless-react-native
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

And then in the simulator after add the code at the Readme:

Invariant Violation: Native module cannot be null.

**Comment by Valodya** [comment]
Please move the topic to our support forum https://support.backendless.com/  
I'm going to close the issue.
